name: CI Cronjob

on:
  # Run this workflow on day 10 of every month as the repo isn't that active.
  schedule:
    - cron: '0 0 10 * *'

permissions: {}

jobs:
  QA:
    # Don't run the cron job on forks.
    if: ${{ github.event.repository.fork == false }}

    uses: ./.github/workflows/reusable-qa-checks.yml
